version: "3.9"
services:
  console:
    container_name: mq-console
    image: apacherocketmq/rocketmq-console:2.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "JAVA_OPTS=-Drocketmq.namesrv.addr=host.docker.internal:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    ports:
      - 8080:8080
  broker:
    container_name: mq-broker-slave
    image: apacherocketmq/rocketmq-broker-slave:2.0.0
    environment:
      - "JAVA_OPT=-server -Xms512m -Xmx512m -Xmn512m"
    extra_hosts:
      - "host.docker.internal:host-gateway"